In [4]:
import numpy

In [6]:
array_ones=numpy.ones((3,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
array_zero=numpy.zeros((5,4))
print(array_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
array_arange=numpy.arange(5,22)
print(array_arange)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


In [15]:
array_diff=numpy.arange(5,22,3)
print(array_diff)

[ 5  8 11 14 17 20]


In [17]:
array_4num = numpy.linspace(1,15,4)
print(array_4num)

[ 1.          5.66666667 10.33333333 15.        ]
