# 1.Installation of NumPy
```C:\Users\Your Name>pip install numpy```
# 2.Import NumPy
Once NumPy is installed, import it in your applications by adding the importkeyword:
```import numpy```

In [1]:
import numpy

# 3.Create a NumPy ndarray Object
4. Create an array containing '1' as its items using the 'ones()' function from the 'numpy' module.

In [4]:
array_ones = numpy.ones((3,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


5. Using 'zeros()' function, create a NumPy array having 4 blocks, 2 rows and 3 columns. The items should be int data-type.

In [21]:
array_zeros = numpy.zeros((4,2,3), dtype = int)
print(array_zeros)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


6. Create  a  one-dimensional  array  containing  numbers  between  5  and  20  using  the 'arrange()' function in the NumPy module.

In [9]:
array_arange = numpy.arange(5,21)
print(array_arange)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


7. Create  an  array  of  numbers  from1  to  24  such  that  the  difference  between  two consecutive  numbers  is  4.  Create  an  array  of  numbers  from  1  to  24  such  that  the difference between two consecutive numbers is 4 and each item is a float.

In [23]:
array_cons_diff = numpy.arange(1,25,4, dtype = float)
print(array_cons_diff)

[ 1.  5.  9. 13. 17. 21.]


8. Create an array containing 4 numbers between 1 to 25.

In [24]:
array_4_num = numpy.linspace(1,25,4)
print(array_4_num)

[ 1.  9. 17. 25.]


9. Create  an  array  containing  10  numbers  between  1  and  25  such  that  the  difference between two consecutive numbers is constant.

In [16]:
array_10_num = numpy.linspace(1,25,10)
print(array_10_num)

[ 1.          3.66666667  6.33333333  9.         11.66666667 14.33333333
 17.         19.66666667 22.33333333 25.        ]


10. Create a three-dimensional NumPy array containing 40 random integers between 50 and 100

In [28]:
array_3d = numpy.random.randint(50,100,40)
array_3d = array_3d.reshape(4,5,2)
print(array_3d)

[[[70 88]
  [69 97]
  [72 99]
  [95 92]
  [86 82]]

 [[64 99]
  [84 55]
  [57 64]
  [58 74]
  [60 78]]

 [[73 51]
  [76 82]
  [55 83]
  [92 87]
  [61 54]]

 [[88 62]
  [53 83]
  [98 74]
  [53 64]
  [87 96]]]


11. Create a list of natural numbers from 1 to 15using the list comprehension method. Then convert the list into a NumPy array using the array() function.

In [18]:
list_natural = [i for i in range(1,16)]
print(list_natural)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


12. Create a function to check whether the input lenghts represent the lengths of the side of a triangle.

In [ ]:
def check_triangle(a,b,c):
    if a+b>c and a+c>b and b+c>a:
        print("The lengths represent the lengths of the side of a triangle")
    else:
        print("The lengths do not represent the lengths of the side of a triangle")

13. Create a function to calculate the area of a triangle using the Heron's formula.

In [ ]:
def area_triangle(a,b,c):
    s = (a+b+c)/2
    area = (s*(s-a)*(s-b)*(s-c))**0.5
    print("The area of the triangle is: ",area)

14. Write a program to perform following two tasks:
- Print the square root of numbers in the list.
- Compute the value of c in the equation c=(√a2+b2).

In [19]:
list_num = [1,4,9,16,25,36,49,64,81,100]
for i in list_num:
    print(i**0.5)

a = 3
b = 4
c = (a**2+b**2)**0.5
print(c)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
5.0


15. Write a program to change the dimension of an array (say my_arr =[1, 2, 3, 4, 5, 6, 7, 8, 9]) into a 3 X 3 (3 rows and 3 columns) array and convert this NumPy array into a list.

In [20]:
my_arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
my_arr = numpy.array(my_arr)
my_arr = my_arr.reshape(3,3)
print(my_arr)
my_arr = my_arr.tolist()
print(my_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
